[package]
name = "twenty-postgres-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
[dependencies]
tokio = { version = "1", features = ["full"] }  
pgwire = "0.4"  
serde = { version = "1.0", features = ["derive"] }  
log = "0.4"  
env_logger = "0.9" 

